version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ports:
      - 8123:8124
    volumes:
      - /docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    privileged: true
    network_mode: host

  mosquitto:
    container_name: mqtt
    image: "eclipse-mosquitto:latest"
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /docker/mosquitto/config:/mosquitto/config
      - /docker/mosquitto/data:/mosquitto/data
      - /docker/mosquitto/log:/mosquitto/log
    restart: unless-stopped
    privileged: true

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - /docker/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=America/Chicago
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    environment:
      - TZ=America/Chicago
    ports:
      - "1880:1880"
    volumes:
      - /docker/node-red/:/data
(END)
